name: Build
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # penting untuk SonarQube

      - name: Setup JDK for SonarQube
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'  # sesuaikan versi Flutter kamu
          channel: stable

      - name: Install dependencies
        working-directory: tubes_mobpro
        run: flutter pub get

      - name: Run Unit Tests # optional
        working-directory: tubes_mobpro
        run: flutter test \test\

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: tubes_mobpro
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.projectName=${{ github.repository }}
            -Dsonar.sources=lib
            -Dsonar.tests=test
            -Dsonar.dart.analyzer.mode=FLUTTER
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.dart.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
