name: Build
on:
  push:
    branches:
      - haidar
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: haidar
          fetch-depth: 0  # penting untuk SonarQube

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'  # sesuaikan versi Flutter kamu

      - name: Install dependencies
        working-directory: ./tubes_mobpro
        run: flutter pub get

      - name: Analyze (optional)
        working-directory: ./tubes_mobpro
        run: flutter analyze

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./tubes_mobpro
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
